# Generated by Django 5.2.8 on 2025-11-30 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('reps_weight', 'Reps and Weight'), ('time_weight', 'Time and Weight')], max_length=20)),
                ('description', models.TextField(help_text='Description of how to perform the exercise')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight (can be positive or negative)', max_digits=10)),
                ('reps', models.PositiveIntegerField(blank=True, help_text='Number of reps (required for reps_weight type)', null=True)),
                ('time_seconds', models.PositiveIntegerField(blank=True, help_text='Time in seconds (required for time_weight type)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['-created_at'],
            },
        ),
    ]
